


 const carsData = [
  {
    id: 1,
    name: "Toyota Corolla",
    price: "$20,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "30,000 km",
    color: "White",
    engine: "1.8L",
    description: "A reliable and fuel-efficient sedan.",
    image: ["https://dealer26407.dealeron.com/blogs/6087/wp-content/uploads/2024/10/2020-Toyota-Corolla.jpg",

"https://images.cars.com/cldstatic/wp-content/uploads/03-toyota-corolla-2020-angle--exterior--grey--rear.jpg",

"https://d2v1gjawtegg5z.cloudfront.net/uploads/files/000/069/367/original/Screen_Shot_2020-06-08_at_10.40.21_AM.jpg?1591627258"
    ],
    sellerName: "James Anderson",
    sellerPhone: "+234 801 234 5678",
    sellerLocation: "Lagos, Nigeria",
    sellerImage: "https://static.vecteezy.com/system/resources/thumbnails/043/210/041/small_2x/portrait-of-a-confident-young-black-man-for-lifestyle-or-fashion-marketing-free-photo.jpeg"
  },
  {
    id: 2,
    name: "Honda Civic",
    price: "$22,500",
    year: 2021,
    transmission: "Manual",
    fuel: "Petrol",
    mileage: "25,000 km",
    color: "Black",
    engine: "2.0L",
    description: "Sporty compact car with great handling.",
    image: ["https://images.cars.com/cldstatic/wp-content/uploads/2020-Honda-Civic-Si-Coupe.jpg",
      "https://images.cars.com/cldstatic/wp-content/uploads/honda-civic-si-2020-47-angle--exterior--rear--red.jpg"
    ],
    sellerName: "Sarah Johnson",
    sellerPhone: "+234 802 345 6789",
    sellerLocation: "Abuja, Nigeria",
    sellerImage: "https://img.freepik.com/free-photo/smiley-african-woman-with-golden-earrings_23-2148747979.jpg?semt=ais_incoming&w=740&q=80"
  },
  {
    id: 3,
    name: "BMW 3 SERIRES",
    price: "$27,000",
    year: 2018,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "60,000 km",
    color: "Red",
    engine: "5.0L V8",
    description: "A powerful German car with style.",
    image: ["https://www.jonathanmotorcars.com/imagetag/1299/2/l/Used-2018-BMW-3-Series-320i-xDrive-1620872809.jpg",],
    sellerName: "Michael Brown",
    sellerPhone: "+234 803 456 7890",
    sellerLocation: "Port Harcourt, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/67.jpg"
  },
  {
    id: 4,
    name: "Mercedes-Benz C-Class",
    price: "$40,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "12,000 km",
    color: "Silver",
    engine: "2.0L Turbo",
    description: "Luxury sedan with advanced tech and comfort.",
    image: ["https://www.thecarexpert.co.uk/wp-content/uploads/2021/12/Mercedes-Benz-C-Class-1920x960.jpg",],
    sellerName: "Linda Smith",
    sellerPhone: "+234 804 567 8901",
    sellerLocation: "Enugu, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/23.jpg"
  },
  {
    id: 5,
    name: "AUDI A4",
    price: "$24,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "70,000 km",
    color: "Blue",
    engine: "2.0L Turbo",
    description: "The ultimate driving machine with sporty features.",
    image: ["https://www.cnet.com/a/img/resize/5a655ac0a04a183ed508b586cec7a6d97e18f64d/hub/2021/01/14/20adf66d-e7c0-48a5-890b-594d571b44f4/a4-ogi.jpg?auto=webp&fit=crop&height=675&width=1200",

      "https://images.nettiauto.com/live/2025/08/20/f00a20690886d415-medium.jpg"
    ],
    sellerName: "Daniel Wilson",
    sellerPhone: "+234 805 678 9012",
    sellerLocation: "Ibadan, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/76.jpg"
  },
  {
    id: 6,
    name: "Ford Mastang",
    price: "$40,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "15,000 km",
    color: "Grey",
    engine: "2.0L Turbo",
    description: "Premium sedan with cutting-edge tech.",
    image: ["https://bringatrailer.com/wp-content/uploads/2024/01/2022_ford_mustang-gt_img_2542-1-65185.jpg?fit=940%2C627",

      "https://www.netcarshow.com/Ford-Mustang_Ice_White_Edition-2022-1280-db8fa04f5d71382757b1e43970225357f6.jpg",

      "https://www.netcarshow.com/Ford-Mustang_Ice_White_Edition-2022-1280-27911a1f754d10f27deb141d9039fa0f61.jpg?token=395284c5f111d6d48b5ccd33575a88eb7f22e7c3bb5da006d49a2cd"
    ],
    sellerName: "Emma Davis",
    sellerPhone: "+234 806 789 0123",
    sellerLocation: "Kano, Nigeria",
    sellerImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIq9iqpg2aOywuGNzxOLCa3orRSSP02do1zQ&s"
  },
  {
    id: 7,
    name: "Tesla Model 3",
    price: "$45,000",
    year: 2023,
    transmission: "Automatic",
    fuel: "Electric",
    mileage: "10,000 km",
    color: "White",
    engine: "Electric Motor",
    description: "Electric sedan with autopilot and long range.",
    image: ["https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/92xGaGOE-7-vQsZFixg-(edit).jpg?t=169813288754",

      "https://hips.hearstapps.com/hmg-prod/images/2023-tesla-model-3-103-1671468220.jpeg"
    ],
    sellerName: "David Martinez",
    sellerPhone: "+234 807 890 1234",
    sellerLocation: "Kaduna, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/84.jpg"
  },
  {
    id: 8,
    name: "Hyundai Elantra",
    price: "$19,500",
    year: 2020,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "28,000 km",
    color: "Silver",
    engine: "1.6L",
    description: "Affordable sedan with a comfortable ride.",
    image: ["https://static.overfuel.com/photos/443/161964/202405-5cd77569ec464cb4a02758c6d7341667.webp",
      "https://blog.consumerguide.com/wp-content/uploads/sites/2/2020/03/Screen-Shot-2020-03-16-at-2.37.55-PM-1024x547.png"
    ],
    sellerName: "Sophia White",
    sellerPhone: "+234 808 901 2345",
    sellerLocation: "Benin City, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/12.jpg"
  },
  {
    id: 9,
    name: "Kia Sportage",
    price: "$28,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "22,000 km",
    color: "Black",
    engine: "2.4L",
    description: "Stylish compact SUV with great features.",
    image: ["https://di-uploads-pod37.dealerinspire.com/stevelanderskia/uploads/2021/07/White-Kia-Sportage-parking-lot.jpg",

      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKFVnCSJoRPjk6AmkrZsrCGIauOBZSUskFTA&s"
    ],
    sellerName: "John Lee",
    sellerPhone: "+234 809 012 3456",
    sellerLocation: "Jos, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/91.jpg"
  },
  {
    id: 10,
    name: "Nissan Altima",
    price: "$25,000",
    year: 2020,
    transmission: "CVT",
    fuel: "Petrol",
    mileage: "35,000 km",
    color: "Blue",
    engine: "2.5L",
    description: "A midsize sedan with a smooth ride.",
    image: ["https://media.ed.edmunds-media.com/nissan/altima/2019/oem/2019_nissan_altima_sedan_vc-t-sr_fq_oem_3_1600.jpg",

      
    ],
    sellerName: "Olivia Harris",
    sellerPhone: "+234 810 123 4567",
    sellerLocation: "Owerri, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/30.jpg"
  },
  {
    id: 11,
    name: "Toyota Highlander",
    price: "$40,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "12,000 km",
    color: "Grey",
    engine: "3.5L V6",
    description: "Spacious SUV with comfort and safety.",
    image: ["https://di-uploads-pod6.dealerinspire.com/mariettatoyota/uploads/2022/02/2022-Toyota-Highlander.jpeg",],
    sellerName: "Ethan Clark",
    sellerPhone: "+234 811 234 5678",
    sellerLocation: "Lagos, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/46.jpg"
  },
  {
    id: 12,
    name: "Chevrolet Tahoe",
    price: "$55,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "20,000 km",
    color: "Black",
    engine: "5.3L V8",
    description: "Full-size SUV with powerful performance.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQMB8iuaAuT484ucK0vf9AXeEzPjMvVP_vpw&s",],
    sellerName: "Ava Lewis",
    sellerPhone: "+234 812 345 6789",
    sellerLocation: "Abuja, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/58.jpg"
  },
  {
    id: 13,
    name: "Range Rover Evoque",
    price: "$60,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "10,000 km",
    color: "White",
    engine: "2.0L Turbo",
    description: "Luxury compact SUV with off-road ability.",
    image: ["https://images.clickdealer.co.uk/vehicles/6237/6237813/large2/147866744.jpg",],
    sellerName: "William King",
    sellerPhone: "+234 813 456 7890",
    sellerLocation: "Port Harcourt, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/24.jpg"
  },
  {
    id: 14,
    name: "Porsche 911",
    price: "$110,000",
    year: 2023,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "8,000 km",
    color: "Red",
    engine: "3.0L Twin-Turbo",
    description: "Iconic sports car with thrilling performance.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWLeLhFROrtQl-iODFA7Ar5dSKPs0i17fcfg&s",],
    sellerName: "Emily Young",
    sellerPhone: "+234 814 567 8901",
    sellerLocation: "Enugu, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/37.jpg"
  },
  {
    id: 15,
    name: "Ferrari F8",
    price: "$220,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "5,000 km",
    color: "Yellow",
    engine: "3.9L V8",
    description: "Exotic supercar with blistering speed.",
    image: ["https://global.discourse-cdn.com/forza/original/4X/4/a/0/4a021dae7ccaa3d562e0499686aef357cfed0f8c.jpeg",],
    sellerName: "Noah Scott",
    sellerPhone: "+234 815 678 9012",
    sellerLocation: "Ibadan, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/51.jpg"
  },
  {
    id: 16,
    name: "Lamborghini Huracan",
    price: "$250,000",
    year: 2023,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "3,000 km",
    color: "Green",
    engine: "5.2L V10",
    description: "Exotic Italian supercar with aggressive styling.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM_F0yl3-5ow92UUry2VjeGRJaVM4vmVN3bA&s",],
    sellerName: "Sophia Adams",
    sellerPhone: "+234 816 789 0123",
    sellerLocation: "Kano, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/81.jpg"
  },
  {
    id: 17,
    name: "Mazda CX-5",
    price: "$30,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "22,000 km",
    color: "Grey",
    engine: "2.5L",
    description: "Compact SUV with stylish design and reliability.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVXRV_b23LJAH5cml-7Tt9TMUBHe3P40cqow&s",],
    sellerName: "Benjamin Wright",
    sellerPhone: "+234 817 890 1234",
    sellerLocation: "Lagos, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/33.jpg"
  },
  {
    id: 18,
    name: "Volkswagen Golf",
    price: "$23,000",
    year: 2020,
    transmission: "Manual",
    fuel: "Petrol",
    mileage: "28,000 km",
    color: "Blue",
    engine: "1.4L Turbo",
    description: "Hatchback with solid build quality and comfort.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6gu4EX4eu6wqPDC0dA1sVpu08A9YG5e5BmQ&s",],
    sellerName: "Grace Allen",
    sellerPhone: "+234 818 901 2345",
    sellerLocation: "Abuja, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/29.jpg"
  },
  {
    id: 19,
    name: "Jeep Wrangler",
    price: "$45,000",
    year: 2022,
    transmission: "Manual",
    fuel: "Petrol",
    mileage: "12,000 km",
    color: "Black",
    engine: "3.6L V6",
    description: "Iconic off-road SUV with rugged performance.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqe-Md2wIJXhWsGgDApY6JgBobl2yekxfeUA&s",],
    sellerName: "Henry Walker",
    sellerPhone: "+234 819 012 3456",
    sellerLocation: "Port Harcourt, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/11.jpg"
  },
  {
    id: 20,
    name: "Subaru Outback",
    price: "$33,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "20,000 km",
    color: "Brown",
    engine: "2.5L Boxer",
    description: "All-wheel drive wagon for adventurous families.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5hre3w0idWLwNXKbvTAFpim8o6nAMnVzHcw&s",],
    sellerName: "Amelia Green",
    sellerPhone: "+234 820 123 4567",
    sellerLocation: "Enugu, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/63.jpg"
  },
  {
    id: 21,
    name: "Chevrolet Camaro",
    price: "$77,000",
    year: 2020,
    transmission: "Manual",
    fuel: "Petrol",
    mileage: "15,000 km",
    color: "Yellow",
    engine: "6.2L V8",
    description: "Classic American muscle with raw power.",
    image: ["https://www.heartlandchevrolet.com/blogs/4069/wp-content/uploads/2021/11/2021-Chevrolet-Camaro-09.jpg",],
    sellerName: "Alexander Hill",
    sellerPhone: "+234 821 234 5678",
    sellerLocation: "Ibadan, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/85.jpg"
  },
  {
    id: 22,
    name: "Volvo XC90",
    price: "$50,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "14,000 km",
    color: "Silver",
    engine: "2.0L Turbo Hybrid",
    description: "Safe and luxurious family SUV.",
    image: ["https://i.gaw.to/vehicles/photos/08/46/084668_2018_volvo_XC90.jpg?1024x640",],
    sellerName: "Isabella Moore",
    sellerPhone: "+234 822 345 6789",
    sellerLocation: "Benin City, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/92.jpg"
  },
  {
    id: 23,
    name: "Peugeot 3008",
    price: "$28,500",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "18,000 km",
    color: "White",
    engine: "1.6L Turbo",
    description: "Stylish crossover SUV with modern tech.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkv-3GfnY0kNSLQGEhqIhOjlWExgoHTftnXA&s",],
    sellerName: "Ethan Carter",
    sellerPhone: "+234 823 456 7890",
    sellerLocation: "Kano, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/56.jpg"
  },
  {
    id: 24,
    name: "Jaguar XF",
    price: "$55,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "9,000 km",
    color: "Black",
    engine: "2.0L Turbo",
    description: "Luxury sedan with British elegance.",
    image: ["https://bringatrailer.com/wp-content/uploads/2024/01/2020_jaguar_2020-xf-sportbrake-prestige_2020_jaguar_2020-xf-sportbrake-prestige_008b986a-ac0b-48a1-95fc-37b5542a4256-waoUZ2-57399-57400-scaled.jpg",],
    sellerName: "Charlotte Perez",
    sellerPhone: "+234 824 567 8901",
    sellerLocation: "Owerri, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/77.jpg"
  },
  {
    id: 25,
    name: "Toyota Land Cruiser",
    price: "$70,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "16,000 km",
    color: "White",
    engine: "4.5L V8",
    description: "Legendary off-road SUV with luxury features.",
    image:[ "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRwJwLGdNLqnm_DgAgCm90mxKAPJXJHdIv1Zj3d6bekOIksr5lvmSSYnba33Rl7vMfAnY&usqp=CAU",],
    sellerName: "Matthew Robinson",
    sellerPhone: "+234 825 678 9012",
    sellerLocation: "Kaduna, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/73.jpg"
  },
  {
    id: 26,
    name: "Bentley Continental GT",
    price: "$200,000",
    year: 2023,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "4,000 km",
    color: "Blue",
    engine: "6.0L W12",
    description: "Ultra-luxury grand tourer with elegance.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Kr-bmoAfvfjU8YjijCj5F7w2Nm0i6an7Xx3FqXINe5OyeB4uOk65nJr0SQg1OWnQvUA&usqp=CAU",],
    sellerName: "Victoria Evans",
    sellerPhone: "+234 826 789 0123",
    sellerLocation: "Jos, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/17.jpg"
  },
  {
    id: 27,
    name: "Rolls-Royce Phantom",
    price: "$350,000",
    year: 2023,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "2,000 km",
    color: "Black",
    engine: "6.75L V12",
    description: "Flagship of luxury cars with unmatched prestige.",
    image: ["https://media.ed.edmunds-media.com/rolls-royce/phantom/2025/oem/2025_rolls-royce_phantom_sedan_base_fq_oem_1_1600.jpg",],
    sellerName: "Christopher Turner",
    sellerPhone: "+234 827 890 1234",
    sellerLocation: "Lagos, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/44.jpg"
  },
  {
    id: 28,
    name: "Mitsubishi Pajero",
    price: "$32,000",
    year: 2020,
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "30,000 km",
    color: "Grey",
    engine: "3.2L Turbo Diesel",
    description: "Tough SUV with off-road performance.",
    image: ["https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/AdskYtUSQ86cqfZE2G2W",],
    sellerName: "Hannah Baker",
    sellerPhone: "+234 828 901 2345",
    sellerLocation: "Abuja, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/48.jpg"
  },
  {
    id: 29,
    name: "Ford Explorer",
    price: "$38,000",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "22,000 km",
    color: "Blue",
    engine: "2.3L Turbo",
    description: "Family-friendly SUV with advanced safety.",
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFEZPjpQavx5DdmYH9WmlRUASgNvgfXbr4mg&s",],
    sellerName: "Joshua Campbell",
    sellerPhone: "+234 829 012 3456",
    sellerLocation: "Port Harcourt, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/men/15.jpg"
  },
  {
    id: 30,
    name: "Alfa Romeo Giulia",
    price: "$48,000",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    mileage: "11,000 km",
    color: "Red",
    engine: "2.9L V6 Twin-Turbo",
    description: "Italian sports sedan with striking looks.",
    image: ["https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/knbkxckopidnhic3a9ii",],
    sellerName: "Mia Rodriguez",
    sellerPhone: "+234 830 123 4567",
    sellerLocation: "Enugu, Nigeria",
    sellerImage: "https://randomuser.me/api/portraits/women/25.jpg"
  }
];

module.exports = carsData;